traits:
  description: Names and details of invertebrate traits included in the AusTraits compilation
  type: list
  elements:
    body_length:
      description: length of body, taken from most anterior point, to most posterior point of main body segments, not including wings or legs
      type: numeric
      units: mm
      label: body length
      values:
        minimum: 0.01
        maximum: 500.0
    dispersal_syndrome:
      description: mode of movement through the landscape
      type: categorical
      label: dispersal syndrome
      values:
        active_flight: powered flight
        selfpropelled_movement_over_land:	sliding, walking, jumping, hopping, running
        phoretic: on another organism
        wind_dispersed: ballooning, aeroplankton
        aquatic_flow: passively in water
        aquatic_swimming: self-prepelled
      keywords: movement
      references: Thurman_2021 [doi.org/]
    shelter_microhabitat:
      description: shelter site
      type: categorical
      label: shelter microhabitat
      values:
        herbaceous: change
